version: "3.8"

services:
  text-analysis:
    build: .
    container_name: text_analysis_container
    volumes:
      - ./data:/app/data
      - ./scripts:/app/scripts
    working_dir: /app
    stdin_open: true
    tty: true
    command: ["bash"]
